### ISSUE TITLE
Give an example to validate an email address

### ISSUE THREAD

**Issue by intonarumori** [adamwaite/Validator#114] opened 2018-11-20 13:10 UTC
Please give a straightforward example to validate an email string: `let email: String?`

Let's check for a value first (required) then for pattern (valid email address)

From the many examples it's not clear how to do it.
I was only able to do it by unwrapping the value first, but that just defeats the purpose of the library.

Also, you give some examples with `ValidationError` but that class is nowhere to be found.
Please consider including it as a helper class and rewriting the examples with them instead of `someValidationErrorType`.

**Comment by adamwaite** [comment] 2019-06-05 19:24
Duplicate of https://github.com/adamwaite/Validator/issues/90. Fixing now.

**Closed by adamwaite** 2019-06-05 19:24 UTC
