### ISSUE TITLE
Swift 4.1 issue

### ISSUE THREAD

**Issue by rockyftn** [adamwaite/Validator#93] opened 2018-03-30 06:56 UTC
I have a problem with building last version of library with last SDK 11.3. The issue is following:
UISlider+Validator doesn't confirm to protocol function ValidateabeInterfaceElement, also same issue is for UITextField and UITextView

**Comment by senthilhisto** [comment] 2018-03-30 14:46
I am also facing the same issue with latest XCode 9.3

**Comment by piv199** [comment] 2018-03-31 16:11
@adamwaite do you have any suggestions on this problem?

**Comment by nderkach** [comment] 2018-03-31 21:58
Not sure, what exactly is the cause of it (the protocol has a default implementation), but here is a temporary workaround: https://github.com/nderkach/Validator/commit/61d24d3618535e21b0f9166fdd862f30acc3644b

**Comment by adamwaite** [comment] 2018-03-31 22:35
Hi guys. I’m travelling Asia with little to no internet. If you could use @nderkach’s solution for now? Maybe make a PR? Thanks

**Comment by Lopdo** [comment] 2018-04-01 07:48
I created PR (https://github.com/adamwaite/Validator/pull/94) based on @nderkach code (shameless copy&paste). It is quick and imho dirty fix. As far as I understand, this isn't how this issue should be resolved, but I was unable to wrap my head around issue sufficiently to come up with proper fix. 
This should work for now, but I am not sure how robust it is.

For other people having same issue (which is all of us :), you can update your pod by replacing

`pod 'Validator'`

with 

`pod 'Validator', :git => 'https://github.com/Lopdo/Validator.git', :commit => '93de2ee18b30c431a26c6c9ca0dd89d7ee546769'`

until @adamwaite gets back from his travels and merges PR or creates proper fix and updates pod.

**Comment by ARGAMX** [comment] 2018-04-04 08:08
facing the same issue with latest XCode 9.3

**Comment by kiokumicu** [comment] 2018-04-05 15:03
Got error on Carthage install

`Validator.xcworkspace -scheme Validator -configuration Release -derivedDataPath /Users/kiokumicu/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/Validator/v3.0.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/yz/gbww569n12xf3gxg_yvfr86m0000gn/T/Validator SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO`

**Comment by eligat** [comment] 2018-04-09 09:26
Probably relates to [this](https://bugs.swift.org/browse/SR-6650)

**Comment by adamwaite** [comment] 2018-04-09 09:46
Hi. I'm back in the UK and will be looking at solving this issue as soon as possible (this evening if I get chance). Thanks for your patience!

**Comment by Lopdo** [comment] 2018-04-09 09:48
Don't worry too much, we have workarounds :) Hope you enjoyed your vacation. I just want to mention once more that my PR is not correct solution, just a quick hack to get it working. I wasn't able to figure out proper fix in time I could devote to it, sorry.

**Comment by adamwaite** [comment] 2018-04-09 20:46
Fixed in 3.0.2

https://github.com/adamwaite/Validator/commit/8c39339af8745853f142f56203f05689835d2816.

I'm not completely happy with the solution, but I couldn't figure any other way without having to explicitly implement in all adopting UI element types.

**Closed by adamwaite** 2018-04-09 20:46 UTC
